import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { PurchaseWithItems } from '../types/models'

/** Brand teal ~#137A63 (screenshot reference) */
const BRAND = { r: 19, g: 122, b: 99 } as const
const SLATE = { r: 51, g: 65, b: 85 } as const
const MUTED = { r: 100, g: 116, b: 139 } as const
const HEADER_H = 100

export type PurchaseInvoiceLabels = {
  supplierName: string
  supplierPhone?: string
  businessName: string
  fuelName: (fuelTypeId: number) => string
}

export function openPurchaseInvoicePdf(detail: PurchaseWithItems, labels: PurchaseInvoiceLabels) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'pt', format: 'a4' })
  const pageW = doc.internal.pageSize.getWidth()
  const margin = 48

  doc.setFillColor(BRAND.r, BRAND.g, BRAND.b)
  doc.rect(0, 0, pageW, HEADER_H, 'F')

  doc.setTextColor(255, 255, 255)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(26)
  doc.text('Invoice', margin, 44)

  doc.setFontSize(20)
  doc.text((labels.businessName || 'Business').toUpperCase(), pageW / 2, 40, { align: 'center' })

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(230, 245, 242)
  doc.text(
    detail.purchaseDate ? new Date(detail.purchaseDate).toLocaleString() : '—',
    pageW / 2,
    60,
    { align: 'center' },
  )

  let y = HEADER_H + 28

  doc.setTextColor(SLATE.r, SLATE.g, SLATE.b)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(9)
  doc.text('SUPPLIER', margin, y)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(11)
  doc.text(labels.supplierName, margin, y + 16)
  if (labels.supplierPhone?.trim()) {
    doc.setFontSize(10)
    doc.setTextColor(MUTED.r, MUTED.g, MUTED.b)
    doc.text(labels.supplierPhone.trim(), margin, y + 32)
  }

  const invNo = String(detail.invoiceNo || detail.id)
  doc.setTextColor(BRAND.r, BRAND.g, BRAND.b)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(22)
  const rightX = pageW - margin
  doc.text(invNo, rightX, y + 8, { align: 'right' })

  y += labels.supplierPhone?.trim() ? 52 : 40

  const activeLines = detail.items.filter((i) => !i.isDeleted)
  const body = activeLines.map((i) => [
    labels.fuelName(i.fuelTypeId),
    Number(i.liters).toFixed(2),
    Number(i.pricePerLiter).toFixed(2),
    Number(i.totalAmount).toFixed(2),
  ])
  const total = activeLines.reduce((s, i) => s + Number(i.totalAmount), 0)

  autoTable(doc, {
    startY: y,
    head: [['Product', 'Liters', 'Unit price', 'Amount']],
    body: body.length ? body : [['—', '—', '—', '0.00']],
    foot: [['', '', 'Total', total.toFixed(2)]],
    theme: 'plain',
    styles: {
      fontSize: 10,
      cellPadding: { top: 10, bottom: 10, left: 8, right: 8 },
      textColor: [SLATE.r, SLATE.g, SLATE.b],
      lineColor: [226, 232, 240],
      lineWidth: 0.5,
    },
    headStyles: {
      fillColor: [241, 245, 249],
      textColor: [MUTED.r, MUTED.g, MUTED.b],
      fontStyle: 'bold',
      fontSize: 8,
      cellPadding: { top: 8, bottom: 8, left: 8, right: 8 },
    },
    columnStyles: {
      0: { cellWidth: 'auto' },
      1: { halign: 'right', cellWidth: 72 },
      2: { halign: 'right', cellWidth: 80 },
      3: { halign: 'right', cellWidth: 88, fontStyle: 'bold' },
    },
    footStyles: {
      fillColor: [236, 253, 245],
      textColor: [BRAND.r, BRAND.g, BRAND.b],
      fontStyle: 'bold',
      fontSize: 11,
    },
    alternateRowStyles: { fillColor: [252, 252, 252] },
    margin: { left: margin, right: margin },
  })

  const d = doc as jsPDF & { lastAutoTable?: { finalY: number } }
  const finalY = d.lastAutoTable?.finalY ?? y + 120
  const totalPages = doc.getNumberOfPages()
  doc.setPage(totalPages)

  const footerY = Math.min(finalY + 36, doc.internal.pageSize.getHeight() - margin)
  doc.setDrawColor(BRAND.r, BRAND.g, BRAND.b)
  doc.setLineWidth(0.75)
  doc.line(margin, footerY - 8, pageW - margin, footerY - 8)

  doc.setFontSize(8)
  doc.setTextColor(MUTED.r, MUTED.g, MUTED.b)
  doc.setFont('helvetica', 'italic')
  doc.text('Generated by Gas Station Management', margin, footerY + 6)
  doc.text(`Page | ${totalPages}`, pageW - margin, footerY + 6, { align: 'right' })

  const blob = doc.output('blob')
  const url = URL.createObjectURL(blob)
  const w = window.open(url, '_blank', 'noopener,noreferrer')
  if (!w) {
    const a = document.createElement('a')
    a.href = url
    a.download = `purchase-${detail.invoiceNo || detail.id}.pdf`
    a.click()
  }
  window.setTimeout(() => URL.revokeObjectURL(url), 120_000)
}
