import { useMemo, useState } from 'react'
import {
  useAutoGenerateDefaultParentAccountsMutation,
  useCreateAccountMutation,
  useDeleteAccountMutation,
  useGetAccountsQuery,
  useGetAccountParentCandidatesQuery,
  useGetBusinessesQuery,
  useGetChartsOfAccountsQuery,
  useUpdateAccountMutation,
} from '../../app/api/apiSlice'
import { useAppSelector } from '../../app/hooks'
import { DataTable, type Column } from '../../components/DataTable'
import { FormSelect, type SelectOption } from '../../components/FormSelect'
import { Modal } from '../../components/Modal'
import { useDeleteConfirm } from '../../hooks/useDeleteConfirm'
import { usePagePermissionActions } from '../../hooks/usePagePermissionActions'
import { useDebouncedValue } from '../../lib/hooks'
import { filterAccountsForViewer } from '../../lib/accountScope'
import { showBusinessPickerInForms } from '../../lib/stationContext'
import type { Account, AccountWriteRequest } from '../../types/models'

export function ChartOfAccountsPage() {
  const { canCreate: routeCanCreate, canUpdate: routeCanUpdate } = usePagePermissionActions()
  const role = useAppSelector((s) => s.auth.role)
  const authBusinessId = useAppSelector((s) => s.auth.businessId)
  const showBizPicker = showBusinessPickerInForms(role)

  const [page, setPage] = useState(1)
  const [pageSize, setPageSize] = useState(50)
  const [search, setSearch] = useState('')
  const debounced = useDebouncedValue(search, 350)
  const [filterBusinessId, setFilterBusinessId] = useState<number | null>(authBusinessId ?? null)

  const businessQueryId = showBizPicker ? (filterBusinessId ?? undefined) : (authBusinessId ?? undefined)
  const accountsQuerySkipped = !showBizPicker && (authBusinessId == null || authBusinessId <= 0)
  const { data, isFetching } = useGetAccountsQuery(
    { page, pageSize, q: debounced || undefined, businessId: businessQueryId },
    { skip: accountsQuerySkipped },
  )
  const { data: chartsOfAccounts } = useGetChartsOfAccountsQuery({})
  const { data: businesses } = useGetBusinessesQuery({ page: 1, pageSize: 500, q: undefined })

  const [createAccount, { isLoading: creating }] = useCreateAccountMutation()
  const [updateAccount, { isLoading: updating }] = useUpdateAccountMutation()
  const [deleteAccount] = useDeleteAccountMutation()
  const [autoGenerate, { isLoading: generating }] = useAutoGenerateDefaultParentAccountsMutation()

  const [open, setOpen] = useState(false)
  const [editing, setEditing] = useState<Account | null>(null)
  const [selected, setSelected] = useState<Set<number>>(new Set())
  const [form, setForm] = useState<AccountWriteRequest>({
    name: '',
    code: '',
    chartsOfAccountsId: 0,
    parentAccountId: null,
    businessId: undefined,
  })
  /** SuperAdmin chooses business in the form; Admin / Accountant always use `businessId` from the JWT (auth slice). */
  const effectiveBusinessIdForScope = showBizPicker ? form.businessId : authBusinessId
  const { requestDelete, dialog: deleteDialog } = useDeleteConfirm()

  const parentBusinessId = editing?.businessId ?? effectiveBusinessIdForScope ?? null
  const { data: parentCandidatesList = [], isFetching: loadingParentCandidates } = useGetAccountParentCandidatesQuery(
    { businessId: parentBusinessId! },
    { skip: !open || parentBusinessId == null || parentBusinessId <= 0 },
  )

  const businessOptions: SelectOption[] = useMemo(
    () => (businesses?.items ?? []).map((b) => ({ value: String(b.id), label: b.name })),
    [businesses?.items],
  )
  const businessNameById = useMemo(() => {
    const m = new Map<number, string>()
    for (const b of businesses?.items ?? []) m.set(b.id, b.name)
    return m
  }, [businesses?.items])

  const tableRows = data?.items ?? []
  const visibleRows = useMemo(
    () => {
      const scoped = filterAccountsForViewer(tableRows, role, authBusinessId)
      if (role === 'SuperAdmin') return scoped
      // Admin/Accountant: show all accounts linked to their business, including top-level (no parent).
      return scoped.filter((a) => a.businessId != null)
    },
    [tableRows, role, authBusinessId],
  )

  const parentCandidatesForForm = useMemo(() => {
    if (role === 'SuperAdmin') return parentCandidatesList
    const allowedBusinessId = authBusinessId ?? parentBusinessId ?? null
    if (allowedBusinessId == null || allowedBusinessId <= 0) return []
    // Admin/Accountant can use shared global parents + business parents.
    return parentCandidatesList.filter((a) => a.businessId == null || a.businessId === allowedBusinessId)
  }, [role, parentCandidatesList, authBusinessId, parentBusinessId])

  const parentOptions: SelectOption[] = useMemo(
    () =>
      parentCandidatesForForm.map((a) => ({
        value: String(a.id),
        label: `${a.code} - ${a.name}${a.businessId == null ? ' (global)' : ''}`,
      })),
    [parentCandidatesForForm],
  )

  const typeOptions: SelectOption[] = useMemo(
    () => (chartsOfAccounts ?? []).map((c) => ({ value: String(c.id), label: c.type })),
    [chartsOfAccounts],
  )

  const cols: Column<Account>[] = useMemo(() => {
    const base: Column<Account>[] = [
      { key: 'code', header: 'Code' },
      { key: 'name', header: 'Account Name' },
      { key: 'type', header: 'Type', render: (r) => r.chartsOfAccounts?.type ?? '—' },
    ]
    if (role === 'SuperAdmin') {
      base.push({
        key: 'parentAccountId',
        header: 'Parent',
        render: (r) => (r.parentAccountId ? `${r.parentAccountId}` : '—'),
      })
    }
    if (showBizPicker) {
      base.splice(2, 0, {
        key: 'businessId',
        header: 'Business',
        render: (r) =>
          r.businessId == null ? '-------' : (businessNameById.get(r.businessId) ?? `ID ${r.businessId}`),
      })
    }
    return base
  }, [showBizPicker, businessNameById, role])

  const businessSelectValue =
    businessOptions.find((o) => o.value === String(form.businessId ?? '')) ?? null
  const parentSelectValue = parentOptions.find((o) => o.value === String(form.parentAccountId ?? '')) ?? null
  const typeSelectValue = typeOptions.find((o) => Number(o.value) === form.chartsOfAccountsId) ?? null
  const filterBusinessValue = businessOptions.find((o) => o.value === String(filterBusinessId ?? '')) ?? null

  const isGlobalAccountForm =
    Boolean(editing && editing.businessId == null) ||
    Boolean(!editing && showBizPicker && !form.businessId)
  const showTypeField =
    isGlobalAccountForm || (role === 'SuperAdmin' && !isGlobalAccountForm && !form.parentAccountId)
  const showParentField = !isGlobalAccountForm

  function closeModal() {
    setOpen(false)
  }

  function openCreate() {
    setEditing(null)
    setForm({
      name: '',
      code: '',
      chartsOfAccountsId: 0,
      parentAccountId: null,
      businessId: undefined,
    })
    setOpen(true)
  }

  function openEdit(row: Account) {
    setEditing(row)
    setForm({
      name: row.name,
      code: row.code,
      chartsOfAccountsId: row.chartsOfAccountsId,
      parentAccountId: row.parentAccountId ?? null,
      businessId: row.businessId ?? undefined,
    })
    setOpen(true)
  }

  async function save() {
    const name = form.name?.trim()
    const code = form.code?.trim()
    if (!name || !code) return

    try {
      if (editing) {
        if (editing.businessId == null) {
          if (form.chartsOfAccountsId <= 0) return
          const body: AccountWriteRequest = {
            name,
            code,
            chartsOfAccountsId: form.chartsOfAccountsId,
            parentAccountId: null,
            businessId: null,
          }
          await updateAccount({ id: editing.id, body }).unwrap()
        } else {
          const parent = form.parentAccountId ? parentCandidatesForForm.find((x) => x.id === form.parentAccountId) : null
          if (form.parentAccountId && !parent) return
          if (!form.parentAccountId && role !== 'SuperAdmin') return
          if (!form.parentAccountId && form.chartsOfAccountsId <= 0) return
          const body: AccountWriteRequest = {
            name,
            code,
            chartsOfAccountsId: parent?.chartsOfAccountsId ?? form.chartsOfAccountsId,
            parentAccountId: form.parentAccountId ?? null,
            businessId: editing.businessId ?? null,
          }
          await updateAccount({ id: editing.id, body }).unwrap()
        }
      } else if (showBizPicker && !form.businessId) {
        if (form.chartsOfAccountsId <= 0 || form.parentAccountId) return
        await createAccount({
          name,
          code,
          chartsOfAccountsId: form.chartsOfAccountsId,
          parentAccountId: null,
          businessId: null,
        }).unwrap()
      } else {
        const bid = effectiveBusinessIdForScope
        if (!bid) return
        const parent = form.parentAccountId ? parentCandidatesForForm.find((x) => x.id === form.parentAccountId) : null
        if (form.parentAccountId && !parent) return
        if (!form.parentAccountId && role !== 'SuperAdmin') return
        if (!form.parentAccountId && form.chartsOfAccountsId <= 0) return
        await createAccount({
          name,
          code,
          chartsOfAccountsId: parent?.chartsOfAccountsId ?? form.chartsOfAccountsId,
          parentAccountId: form.parentAccountId ?? null,
          businessId: bid,
        }).unwrap()
      }
      setOpen(false)
    } catch (e) {
      console.error(e)
    }
  }

  async function generateDefaultParents() {
    if (!showBizPicker) return
    await autoGenerate().unwrap()
  }

  const effectiveCreateBusinessId = effectiveBusinessIdForScope

  const canSubmitCreate =
    Boolean(form.name?.trim() && form.code?.trim()) &&
    (editing
      ? editing.businessId == null
        ? form.chartsOfAccountsId > 0
        : role === 'SuperAdmin'
          ? Boolean(form.parentAccountId || form.chartsOfAccountsId > 0)
          : Boolean(form.parentAccountId)
      : showBizPicker && !form.businessId
        ? form.chartsOfAccountsId > 0 && !form.parentAccountId
        : role === 'SuperAdmin'
          ? Boolean(effectiveCreateBusinessId && effectiveCreateBusinessId > 0 && (form.parentAccountId || form.chartsOfAccountsId > 0))
          : Boolean(effectiveCreateBusinessId && effectiveCreateBusinessId > 0 && form.parentAccountId))

  return (
    <>
      <DataTable<Account>
        title="Accounts"
        addLabel="Add Account"
        rows={visibleRows}
        totalCount={accountsQuerySkipped ? 0 : (data?.totalCount ?? 0)}
        page={page}
        pageSize={pageSize}
        onPageChange={setPage}
        onPageSizeChange={setPageSize}
        search={search}
        onSearchChange={(q) => {
          setSearch(q)
          setPage(1)
        }}
        columns={cols}
        isLoading={isFetching}
        selectedIds={selected}
        onSelectedIdsChange={setSelected}
        onAdd={openCreate}
        onEdit={openEdit}
        onDeleteOne={(id) =>
          requestDelete({
            title: 'Delete account?',
            description: 'This account will be soft-deleted.',
            action: async () => {
              await deleteAccount(id).unwrap()
              setSelected((prev) => {
                const next = new Set(prev)
                next.delete(id)
                return next
              })
            },
          })
        }
        onDeleteSelected={() =>
          requestDelete({
            title: 'Delete selected accounts?',
            description: `Delete ${selected.size} selected account(s).`,
            action: async () => {
              await Promise.all(Array.from(selected).map((id) => deleteAccount(id).unwrap()))
              setSelected(new Set())
            },
          })
        }
        extraToolbar={
          showBizPicker ? (
            <div className="flex w-full min-w-0 basis-full flex-col gap-2 sm:basis-auto sm:w-auto sm:flex-row sm:flex-wrap sm:items-stretch lg:basis-auto lg:flex-nowrap lg:items-center lg:gap-2">
              <div className="w-full min-w-0 sm:min-w-44 sm:max-w-56 lg:w-52 lg:max-w-none xl:w-56">
                <FormSelect
                  options={businessOptions}
                  value={filterBusinessValue}
                  onChange={(opt) => {
                    setFilterBusinessId(opt ? Number(opt.value) : null)
                    setPage(1)
                  }}
                  placeholder="Filter business"
                  isClearable
                />
              </div>
              <button
                type="button"
                onClick={generateDefaultParents}
                disabled={generating || !routeCanCreate}
                title={!routeCanCreate ? 'No create permission' : undefined}
                className="w-full shrink-0 whitespace-normal rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2 text-left text-sm font-medium leading-snug text-emerald-700 disabled:opacity-50 sm:w-auto sm:max-w-[16rem] sm:text-center lg:max-w-xs xl:max-w-none"
              >
                {generating ? 'Generating...' : 'Auto-generate parent accounts'}
              </button>
            </div>
          ) : null
        }
      />

      <Modal open={open} onClose={closeModal} title={editing ? 'Edit account' : 'Add account'}>
        <div className="grid grid-cols-1 gap-3 md:grid-cols-2">
          {showBizPicker && (
            <div className="md:col-span-2">
              <label className="mb-1 block text-sm font-medium text-slate-700">Business</label>
              <p className="mb-1 text-xs text-slate-500">
                Leave empty for a new <strong>global</strong> top-level account (type required, no parent). Select a business
                to add a <strong>sub-account</strong> under that business’s parent accounts (parent required; type comes from
                parent).
              </p>
              <FormSelect
                options={businessOptions}
                value={businessSelectValue}
                onChange={(opt) =>
                  setForm((s) => ({
                    ...s,
                    businessId: opt ? Number(opt.value) : undefined,
                    parentAccountId: null,
                    chartsOfAccountsId: opt ? 0 : s.chartsOfAccountsId,
                  }))
                }
                placeholder="No business (global parent)"
                isClearable
              />
            </div>
          )}
          {showTypeField && (
            <div>
              <label className="mb-1 block text-sm font-medium text-slate-700">Type</label>
              <FormSelect
                options={typeOptions}
                value={typeSelectValue}
                onChange={(opt) => setForm((s) => ({ ...s, chartsOfAccountsId: opt ? Number(opt.value) : 0 }))}
                placeholder="Select type"
              />
            </div>
          )}
          <div>
            <label className="mb-1 block text-sm font-medium text-slate-700">Account name</label>
            <input
              value={form.name}
              onChange={(e) => setForm((s) => ({ ...s, name: e.target.value }))}
              className="w-full rounded-lg border border-slate-200 px-3 py-2"
            />
          </div>
          <div>
            <label className="mb-1 block text-sm font-medium text-slate-700">Code</label>
            <input
              value={form.code}
              onChange={(e) => setForm((s) => ({ ...s, code: e.target.value }))}
              className="w-full rounded-lg border border-slate-200 px-3 py-2"
            />
          </div>
          {showParentField && (
            <div className="md:col-span-2">
              <label className="mb-1 block text-sm font-medium text-slate-700">Parent account</label>
              <FormSelect
                options={parentOptions.filter((x) => Number(x.value) !== editing?.id)}
                value={parentSelectValue}
                onChange={(opt) =>
                  setForm((s) => {
                    const parentId = opt ? Number(opt.value) : null
                    const parent = parentId ? parentCandidatesForForm.find((x) => x.id === parentId) : null
                    return {
                      ...s,
                      parentAccountId: parentId,
                      chartsOfAccountsId: parent?.chartsOfAccountsId ?? s.chartsOfAccountsId,
                    }
                  })
                }
                placeholder={loadingParentCandidates ? 'Loading parents…' : 'Select parent'}
                isClearable
              />
              {role === 'SuperAdmin' ? (
                <p className="mt-1 text-xs text-slate-500">Optional for SuperAdmin: leave empty to create a business top-level account.</p>
              ) : null}
              {loadingParentCandidates ? (
                <p className="mt-1 text-xs text-slate-500">Loading parent accounts…</p>
              ) : parentOptions.length === 0 ? (
                <p className="mt-1 text-xs text-amber-800">
                  No parent accounts found. Use <strong>Auto-generate parent accounts</strong> to create shared global parents.
                </p>
              ) : null}
            </div>
          )}
        </div>
        <div className="mt-4 flex justify-end gap-2">
          <button type="button" onClick={closeModal} className="rounded-lg border border-slate-200 px-4 py-2 text-sm">
            Cancel
          </button>
          <button
            type="button"
            disabled={
              creating ||
              updating ||
              !canSubmitCreate ||
              (editing ? !routeCanUpdate : !routeCanCreate)
            }
            title={editing ? (!routeCanUpdate ? 'No update permission' : undefined) : !routeCanCreate ? 'No create permission' : undefined}
            onClick={save}
            className="rounded-lg bg-emerald-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50"
          >
            {editing ? 'Update' : 'Create'}
          </button>
        </div>
      </Modal>
      {deleteDialog}
    </>
  )
}
